replicaCount: 1

image:
  repository: amralaayassen/hostaway-app
  pullPolicy: Always
  tag: "1.0.0"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101

securityContext:
  runAsNonRoot: true
  runAsUser: 101

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
